# https://taskfile.dev

version: '3'

env:
  PROJECT_NAME: ansible-study

tasks:

  default:
    cmds:
      - echo 'try, task local.dev'
    silent: true

  local.dev:
    summary: |
      Run ansible local dev with docker-compose
      eg. task local.dev
    cmds:
      - docker-compose run ansible-control-node

  clean:
    summary: |
      Clean up infrastructure
    cmds:
      - docker-compose down

  docker.build:
    summary: |
      Build ansible control node and managed nodes
    cmds:
      - docker-compose build

  install_commit_hook:
    summary: |
      install commit hook, run it once.
    cmds:
      - pip install pre-commit
      - pre-commit install
      - pre-commit run --all-files

